### ISSUE TITLE
Docker Healthcheck support

### ISSUE THREAD

**Issue by ElleshaHackett** [linuxserver/docker-ubooquity#32]
**Describe the feature**
Being able to see a "health status" of the Ubooquity Docker container or even better on all @linuxserver Docker containers.

**Describe the solution you'd like**
I would like support for the Docker Healthcheck (that is also shown in Portainer.io and probably other Docker management software).

**Describe alternatives you've considered**
Alternative is setting up something similarly without the use of the already existing tools within Docker.

**Additional context**
The `Dockerfile` could contain something like this:

`HEALTHCHECK --interval=60s --timeout=10s --retries=3 CMD (curl -sS http://localhost:2202 && curl -sS http://localhost:2203) || exit 1`. 

For debugging and testing purposses you can use:

`docker inspect --format "{{json .State.Health}}" containername`

![image](https://user-images.githubusercontent.com/5116641/75119686-67c7ae00-5685-11ea-8774-1c7b591f7781.png)

**Comment by j0nnymoe** [comment]
Sorry we don't have any plans to add healthcheck within our containers, ref: https://github.com/linuxserver/docker-tautulli/issues/79#issuecomment-546721863
