### ISSUE TITLE
Heigh CPU load

### ISSUE THREAD

**Issue by jwillmer** [linuxserver/docker-ubooquity#34]
I have a constant 2-6% CPU load when running this image compared to every other images from `linuxserver/..`. I'm happy to help investigating this issue.  Just let me know what kind of data might be useful.

**Comment by kostak79** [comment]
> I have a constant 2-6% CPU load when running this image compared to every other images from `linuxserver/..`. I'm happy to help investigating this issue. Just let me know what kind of data might be useful.

Hello, do you solve your Problem and how?
Got the same issue here.
The issue template link is not active anymore.
Thx

**Comment by jwillmer** [comment]
@kostak79 I solved it by switching to https://github.com/linuxserver/docker-calibre-web

**Comment by kostak79** [comment]
> @kostak79 I solved it by switching to https://github.com/linuxserver/docker-calibre-web

ok ;-)
Thx a lot.
