### ISSUE TITLE
Running reverse proxy, if I click "Comics" it takes me to my router

### ISSUE THREAD

**Issue by paulr24** [linuxserver/docker-ubooquity#36]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

So I have Ubooquity running and it's mostly working properly, but when behind reverse proxy if I click "Comics" it takes me to my router. If I click "Latest Comics" that works perfectly. I noticed that if I browse to Ubooquity using localhost instead of reverse proxy and click "Comics" it takes me there as it should, and it appends "/comics/187724/" to the end of the URL. Over reverse proxy, if I hover over the "Comics" icon I can see that the url just shows "/comics/" at the end, so I assume that some mechanism that appends that number to the end is not working properly. Is there anything I can do to make this work over reverse proxy? Thanks!
------------------------------

## Expected Behavior

When I go to "Comics" it should take me there.
## Current Behavior

When I go to "Comics" it takes me to my router.
## Environment
**OS:**Synology DSM 6
**CPU architecture:** x64
**How docker service was installed:**
from the linuxserver repo

**Comment by j0nnymoe** [comment]
Details of your proxy setup would help.

**Comment by paulr24** [comment]
@j0nnymoe 

I'm just using the internal reverse proxy feature within Synology DSM.

**Comment by j0nnymoe** [comment]
Unfortunately we don't support that method as no one within the team uses it. We only support our own reverse proxy solution here: https://github.com/linuxserver/docker-swag/ which includes a reverse proxy config here: https://github.com/linuxserver/reverse-proxy-confs/blob/master/ubooquity.subdomain.conf.sample .

Take a look at that and see if that info can help with you with the synology solution.
