### ISSUE TITLE
[FEAT] Upgrade to Version 3 (again)

### ISSUE THREAD

**Issue by vonguard** [linuxserver/docker-ubooquity#55]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Upgrade to Version 3 of Ubooquity, despite it only being a beta. It has been almost 12 months since the beta release. Nothing more is coming any time soon and it's a major upgrade.

### Reason for change

Stability, speed, reliability, better overall experience, and again, there seems not to be a stable release coming any time soon. This beta is it. I know you marked this as closed previously, but it's been 10 months since that closure.

**Comment by aptalca** [comment]
https://github.com/linuxserver/docker-ubooquity/issues/47#issuecomment-1784106221

**Comment by logicwar** [comment]
It would be good to have a 2nd and separate docker image for 3.0 (it shouldn't replace 2.1.4). As mentionned above 3.0.2 is almost a year old now.

**Comment by vonguard** [comment]
And now there is a vulnerability in the 2.x branch. Developer is advising all users to update to 2.1.4 or to 3. 3 is a breaking release, also, and requires a complete re scrape of the DB. Advise bumping this to version 2.1.4, then starting a new container project for 3. https://vaemendis.net/ubooquity/article24/vulnerabilty-in-ubooquity-2-1-2-please-update-to-2-1-4-ubooquity-3-is-safe

**Comment by thespad** [comment]
If it's a breaking change to v3 and from what I've read there's no plan to change that, we can't just update latest to v3 because it would break everyone's containers. And we can't do a v3 tag and then switch it, because everyone will keep unknowingly downloading v2.

Equally starting a whole new repo just for v3 feels like the wrong thing to do, so I'm not sure what the best approach is.

**Comment by vonguard** [comment]
Definitely a sticky issue, but tags can help with this: https://www.geeksforgeeks.org/docker-versioning-best-practices/

**Comment by deepdivered** [comment]
Here is the link to the 3.0.2 file which is not located in the beta folder anymore. 

https://vaemendis.net/ubooquity/downloads/Ubooquity-3.0.2.zip

**Comment by thespad** [comment]
The problem isn't the download link, it's that there's no reliable endpoint to query the current version from. At the moment we query vaemendis.net/ubooquity/service/download.php and see what file it tries to return (which is still 2.1.5), but there's no automated way for us to know what the current v3 release version is.
