### ISSUE TITLE
Ubooquity not actually being started up in image.

### ISSUE THREAD

**Issue by hubbcaps** [linuxserver/docker-ubooquity#7]
Ubooquity doesn't actually appear to be launching once the container is stood up on top of this image.

I've had to manually go into the image and create a script based off of Ubooquities own startup shell script and manually start up the app.

Is this intended? Is there some config switch I'm missing?

I'm using Ansible to deploy using the docker container modules, all of your other images deploy fine with this method

hubcaps - % cat roles/ubooquity/tasks/main.yml 
# Setup Ubooquity
- name: ubooq container
  docker_container:
    name: "ubooq"
    image: "linuxserver/ubooquity"
    state: "started"
    restart_policy: "always" 
    volumes:
    - "{{ ubooq_config }}:/config"
    - "{{ host_media }}/books:/books"
    - "{{ host_media }}/comics:/comics"
    - "{{ ubooq_files }}:/files"
    ports:
    - '2202:2202'
    env:
      TZ: "{{ TZ }}"
      PUID: "{{ ubooq_user_id }}"
      PGID: "{{ ubooq_group_id }}"
      MAXMEM: "4096MB"
    log_driver: 'syslog'
    log_opt:
      tag: "ubooq"

**Comment by sparklyballs** [comment]
the image starts with the run command as listed in the README, with the webui showing at
`<ip>:2202/ubooquity`
